# Generated by Django 5.0.1 on 2024-02-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
    ]
