# Generated by Django 5.0.1 on 2024-02-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_user_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
