# Generated by Django 5.0.1 on 2024-02-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='modify_profile_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
