# Generated by Django 5.0.1 on 2024-03-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_useraccount_modify_profile_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
