# Generated by Django 5.0.1 on 2024-03-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_alter_useraccount_modify_profile_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.IntegerField()),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('shiftID', models.AutoField(primary_key=True, serialize=False)),
                ('shiftDate', models.DateField()),
                ('shiftName', models.IntegerField()),
                ('timeStart', models.CharField(max_length=5)),
                ('duration', models.IntegerField()),
                ('timeEnd', models.CharField(max_length=5)),
                ('timeTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.timetable')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='user.useraccount')),
            ],
        ),
    ]
