name: Backend CI

on:
    push:
        branches:
            - main
            - development

jobs:
    tests:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    # The MySQL docker container requires these environment variables to be set
                    # so we can create and migrate the test database.
                    # See: https://hub.docker.com/_/mysql
                    MYSQL_DATABASE: qlns
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    # Opens port 3306 on service container and host
                    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
                    - 3306:3306
                    # Before continuing, verify the mysql container is reachable from the ubuntu host
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - uses: actions/checkout@v3
            - name: Install Ubuntu dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install libcurl4-openssl-dev libmysqlclient-dev libgirepository1.0-dev

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                  python-version: 3.x

            - name: Install Python dependencies
              run: |
                  pip install -r backend/requirements.txt

            - name: Run tests
              # These environment variables will take precedence over the ones in the Django settings file
              env:
                  # Set the DJANGO_SECRET_KEY in the Github repo settings: Go to Secrets and variables > Actions > New repository secret
                  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
                  DATABASE_NAME: qlns
                  DATABASE_USERNAME: root
                  DATABASE_PASSWORD: root
                  DATABASE_ENDPOINT: 127.0.0.1 # Will not work with 'localhost', since that will try a Unix socket connection (!)
              run: |
                  python manage.py migrate
                  python manage.py test
