name: Backend CI

on:
    push:
        branches:
            - main
            - development

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: nienluan2024
                    MYSQL_DATABASE: qlns
                ports:
                    - "3306:3306"

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/backend/requirements.txt

            - name: Run Migrations
              run: |
                  cd backend
                  python manage.py migrate
              env:
                  DBENGINE: django.db.backends.mysql
                  DBNAME: qlns
                  DBUSER: minhtriet
                  DBPASSWORD: nienluan2024
                  DBHOST: mysql
                  DBPORT: "3306"

            - name: Run Tests
              run: |
                  cd backend
                  python manage.py test
              env:
                  DBENGINE: django.db.backends.mysql
                  DBNAME: qlns
                  DBUSER: minhtriet
                  DBPASSWORD: nienluan2024
                  DBHOST: mysql
                  DBPORT: "3306"
