name: Backend CI

on:
    push:
        branches:
            - main
            - development

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        env:
            CI: true

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install Dependencies
              run: |
                  pip install -r backend/backend/requirements.txt

            - name: Install SQLite
              run: |
                  sudo apt-get update
                  sudo apt-get install sqlite3 libsqlite3-dev

            - name: Create SQLite Database
              run: |
                  sqlite3 test.db

            - name: Run Django Migrations
              run: |
                  cd backend
                  python manage.py migrate

            - name: Run Tests
              run: |
                  cd backend
                  python manage.py test shift

            - name: Clean up
              run: |
                  rm -f test.db
