name: Backend CI

on:
    push:
        branches:
            - main
            - development

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: qlns
                    MYSQL_ROOT_PASSWORD: nienluan2024
                ports:
                    - 3306:3306

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/backend/requirements.txt

            - name: Run Migrations
              env:
                  DENGINE: django.db.backends.mysql
                  DATABASE_NAME: qlns
                  DATABASE_USERNAME: minhtriet
                  DATABASE_PASSWORD: nienluan2024
                  DATABASE_ENDPOINT: 127.0.0.1
              run: |
                  cd backend
                  python manage.py migrate

            - name: Run Tests
              env:
                  DENGINE: django.db.backends.mysql
                  DATABASE_NAME: qlns
                  DATABASE_USERNAME: minhtriet
                  DATABASE_PASSWORD: nienluan2024
                  DATABASE_ENDPOINT: 127.0.0.1
              run: |
                  cd backend
                  python manage.py test
